import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#f4f3eb', banner: '#123739', petrol: '#156a65', text: '#172c2b', muted: '#62716e',
  hash: '#244d49', terra: '#a3532e', red: '#a52a1f', sand: '#f2efe6',
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg }, content: { padding: 22, paddingTop: 12, paddingBottom: 54, gap: 18 },
  tabs: { flexDirection: 'row', gap: 8, paddingHorizontal: 22, paddingTop: 12, paddingBottom: 4, backgroundColor: colors.bg },
  tab: { flex: 1, borderRadius: 12, paddingVertical: 11, alignItems: 'center', borderWidth: 1, borderColor: colors.petrol },
  tabActive: { backgroundColor: colors.petrol },
  tabText: { color: colors.petrol, fontWeight: '800', letterSpacing: 0.4 }, tabTextActive: { color: '#fff' },
  hero: { backgroundColor: colors.banner, borderRadius: 24, padding: 26, gap: 15 },
  brand: { color: '#abdac3', fontSize: 11, fontWeight: '800', letterSpacing: 2 },
  title: { fontSize: 38, lineHeight: 43, fontWeight: '700', color: '#f4f3eb' },
  lead: { fontSize: 14, lineHeight: 22, color: '#c4dbd0' },
  heroStats: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 6 },
  heroStat: { color: '#e7d0a5', fontSize: 11, fontWeight: '700', borderWidth: 1, borderColor: '#45716c', borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8 },
  sectionEyebrow: { color: '#39716a', fontSize: 11, fontWeight: '800', letterSpacing: 1.4, marginTop: 7 },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  button: { backgroundColor: colors.petrol, borderRadius: 12, padding: 14 },
  secondary: { borderColor: colors.petrol, borderWidth: 1, borderRadius: 12, padding: 13 },
  buttonText: { color: '#fff', fontWeight: '700' }, secondaryText: { color: colors.petrol, fontWeight: '700' },
  disabled: { opacity: 0.5 }, card: { backgroundColor: '#fff', padding: 16, borderRadius: 16, gap: 12 },
  preview: { width: '100%', height: 230, backgroundColor: '#e9ece9', borderRadius: 10 },
  label: { fontWeight: '700', color: colors.text }, hash: { fontFamily: 'monospace', color: colors.hash },
  muted: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  input: { borderWidth: 1, borderColor: '#b9c9c5', borderRadius: 10, padding: 13, fontSize: 16 },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  switchLabel: { color: colors.text, fontWeight: '600', flex: 1 },
  message: { color: '#204a47', fontWeight: '600' }, footer: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  sectionTitle: { fontSize: 24, fontWeight: '800', color: colors.text },
  historyTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  badge: { overflow: 'hidden', borderRadius: 8, paddingHorizontal: 9, paddingVertical: 5, fontSize: 12, fontWeight: '700' },
  pending: { backgroundColor: '#fff0c2', color: '#725400' }, confirmed: { backgroundColor: '#dcefe9', color: '#145c4f' },
  local: { backgroundColor: '#e7ece8', color: '#345e57' }, failed: { backgroundColor: '#f8dedb', color: '#8c3838' },
  resultBanner: { borderRadius: 16, padding: 18, gap: 8 },
  resultEyebrow: { fontSize: 11, fontWeight: '800', letterSpacing: 1.6 },
  resultTitle: { fontSize: 24, lineHeight: 30, fontWeight: '700' },
  resultText: { fontSize: 13, lineHeight: 20 },
  glanceRow: { flexDirection: 'row', gap: 12, borderTopWidth: 1, borderTopColor: '#e8e2d5', paddingTop: 9 },
  glanceLabel: { width: 96, color: colors.muted, fontSize: 12 },
  glanceValue: { flex: 1, color: colors.text, fontWeight: '700' },
  chainRow: { borderWidth: 1, borderColor: '#ddd5c7', borderRadius: 10, padding: 10, gap: 3 },
  chainTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  small: { fontSize: 11, color: colors.muted },
});
